# Generated by Django 6.0.5 on 2026-05-27 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activity_type', models.CharField(choices=[('outdoor', 'Aire libre'), ('indoor', 'Interior')], default='outdoor', max_length=20)),
                ('desired_conditions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('finished', 'Finalizada'), ('rescheduled', 'Reagendada'), ('cancelled', 'Cancelada')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='planner.location')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StatisticalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('median_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mode_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('regression_slope', models.DecimalField(decimal_places=4, max_digits=8)),
                ('regression_intercept', models.DecimalField(decimal_places=4, max_digits=8)),
                ('trend', models.CharField(choices=[('warming', 'Calentamiento'), ('cooling', 'Enfriamiento'), ('stable', 'Estable')], max_length=20)),
                ('bayes_rain_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('realization_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recommendation', models.CharField(choices=[('do', 'Realizar'), ('review', 'Revisar'), ('postpone', 'Posponer')], default='review', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistical_summary', to='planner.activity')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('temporary_password_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rain_probability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_source', models.CharField(default='OpenWeatherMap', max_length=80)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_records', to='planner.activity')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['activity', 'date'], name='planner_cli_activit_eaf5f9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_location_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['owner', 'date'], name='planner_act_owner_i_eb86b2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['location', 'date'], name='planner_act_locatio_ac3b37_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['status'], name='planner_act_status_2f2e1b_idx'),
        ),
    ]
