# Generated by Django 6.0.5 on 2026-05-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_userprofile_password_reset_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
