# Generated by Django 6.0.5 on 2026-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_userprofile_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticalsummary',
            name='temperature_series',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
